# Generated by Django 4.2.7 on 2024-05-28 11:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shorten_url', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='url',
            name='url_id',
        ),
    ]
