version: '3.7'

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    expose:
      - 8000
    volumes:
      - /home/testserver/exam/static:/app/static
      - /home/testserver/exam/mediafiles:/app/mediafiles
    entrypoint:
      - ./entrypoint.sh


  nginx:
    build: ./nginx

    volumes:
      - /home/testserver/exam/static:/app/static
      - /home/testserver/exam/mediafiles:/app/mediafiles
    ports:
      - 2442:80
    depends_on:
      - web